name: CI - Dream.mf Logging

on:
  pull_request:
    paths:
      - "packages/dmf-logging/**"
      - ".github/workflows/npm-publish-logging.yml"
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: packages/dmf-logging
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install NX CLI
        run: pnpm add -g nx
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm nx build dmf-logging
