name: Publish - Dream.mf React

on:
  push:
    paths:
      - 'packages/dmf-react/**'
      - '.github/workflows/npm-publish-react.yml'
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: packages/dmf-react
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - run: pnpm install
        working-directory: ${{ env.PACKAGE_DIR }}
      - run: pnpm run build
        working-directory: ${{ env.PACKAGE_DIR }}
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
        working-directory: ${{ env.PACKAGE_DIR }}/dist
        shell: bash
      - run: ls -alh ${{ env.PACKAGE_DIR }}/dist
      - run: npm publish --access public
        working-directory: ${{ env.PACKAGE_DIR }}/dist
