name: Publish - Dream.mf AI Docgen

on:
  push:
    paths:
      - "packages/dmf-ai-docgen/**"
      - ".github/workflows/npm-publish-ai-docgen.yml"
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: packages/dmf-ai-docgen
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install NX CLI
        run: pnpm add -g nx
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm nx build dmf-ai-docgen
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
        working-directory: ${{ env.PACKAGE_DIR }}
        shell: bash
      - run: ls -alh ${{ env.PACKAGE_DIR }}
      - run: npm publish --access public
        working-directory: ${{ env.PACKAGE_DIR }}
